version: "3"

services:
  elm:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_USER_IDENTIFIER: $DOCKER_USER_IDENTIFIER
        DOCKER_NODE_VERSION: $DOCKER_NODE_VERSION
        DOCKER_NODE_DISTRIBUTION: $DOCKER_NODE_DISTRIBUTION
        DOCKER_ELM_VERSION: $DOCKER_ELM_VERSION
        DOCKER_ELM_DISTRIBUTION: $DOCKER_ELM_DISTRIBUTION
    entrypoint: elm
    user: user
    tty: true
    stdin_open: true
    working_dir: /home/user
    ports:
      - $VITE_SERVER_HOST:$VITE_SERVER_PORT:$VITE_SERVER_PORT
    volumes:
      - .:/home/user

  npm:
    extends: elm
    entrypoint: npm
