name: Build

on:
  pull_request:
    branches:
      - development

  push:
    branches:
      - development
  
jobs:
  build:
    name: Check that the template can be built
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: cp .env.example .env

      - name: User identifier setup
        run: sed -i "s/DOCKER_USER_IDENTIFIER=.*/DOCKER_USER_IDENTIFIER=\"$(id -u)\"/g" .env

      - name: Build
        run: make production
