name: Build

on: [ push, pull_request ]
  
jobs:
  build:
    name: Check that the template can be built
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: cp .env.example .env

      - name: User identifier setup
        run: sed "s/DOCKER_USER_IDENTIFIER=.*/DOCKER_USER_IDENTIFIER=\"$(id -u)\"/g" .env

      - name: Build
        run: make production
